TECH_MAP = {
    # langs
    "python": "Python",
    "javascript": "JavaScript",
    "js": "JavaScript",
    "typescript": "TypeScript",
    "ts": "TypeScript",
    "golang": "Go",
    "go lang": "Go",
    "rust": "Rust",
    "java": "Java",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "swift": "Swift",
    "php": "PHP",
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "csharp": "C#",
    "ruby": "Ruby",
    # backend frameworks
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "spring": "Spring Boot",
    "spring boot": "Spring Boot",
    "express": "Express.js",
    "nestjs": "NestJS",
    "nest.js": "NestJS",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "asp.net": "ASP.NET",
    "dotnet": ".NET",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    # frontend frameworks
    "react": "React",
    "react.js": "React",
    "reactjs": "React",
    "vue": "Vue.js",
    "vue.js": "Vue.js",
    "vuejs": "Vue.js",
    "angular": "Angular",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "nuxt": "Nuxt.js",
    "html": "HTML5",
    "html5": "HTML5",
    "css": "CSS3",
    "css3": "CSS3",
    "sass": "Sass",
    "tailwind": "Tailwind CSS",
    # dbs
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "clickhouse": "ClickHouse",
    "sqlite": "SQLite",
    "mariadb": "MariaDB",
    "cassandra": "Cassandra",
    # devops
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "ansible": "Ansible",
    "terraform": "Terraform",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "jenkins": "Jenkins",
    "gitlab": "GitLab CI",
    "github actions": "GitHub Actions",
    "aws": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "linux": "Linux",
    "nginx": "Nginx",
    # message queues
    "celery": "Celery",
    "rabbitmq": "RabbitMQ",
    "kafka": "Apache Kafka",
    "apache kafka": "Apache Kafka",
    # ai
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scikit-learn": "Scikit-Learn",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "llm": "LLM",
    "openai": "OpenAI",
    # mobile
    "flutter": "Flutter",
    "react native": "React Native",
    # tools
    "git": "Git",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "rest api": "REST API",
    "rest": "REST API",
}
