"""add_jobs_table

Revision ID: 7cc55ca1c078
Revises: 81fabbe4494a
Create Date: 2026-05-21 13:12:34.682507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc55ca1c078'
down_revision: Union[str, Sequence[str], None] = '81fabbe4494a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('stack', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_jobs_search_vector', 'jobs', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

    # ### manually added: full text search optimization trigger
    op.execute("""
        CREATE OR REPLACE FUNCTION jobs_search_vector_trigger()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(NEW.company, '')), 'B') ||
                setweight(to_tsvector('english', coalesce(array_to_string(NEW.stack, ' '), '')), 'B');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
            """)

    # ### manually added: enable trigger for lifecycle of jobs table
    op.execute("""
        CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
        ON jobs FOR EACH ROW
        EXECUTE FUNCTION jobs_search_vector_trigger();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS vsvectorupdate ON jobs;")
    op.execute("DROP FUNCTION IF EXISTS jobs_search_vector_trigger();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_search_vector', table_name='jobs', postgresql_using='gin')
    op.drop_table('jobs')
    # ### end Alembic commands ###
