"""add source_id to jobs

Revision ID: 7dfe28af890e
Revises: b15bf1ef536a
Create Date: 2026-06-09 11:41:09.846136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfe28af890e'
down_revision: Union[str, Sequence[str], None] = 'b15bf1ef536a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'source_id')
    # ### end Alembic commands ###
